spring.application.name=help_api

spring.data.mongodb.uri=mongodb+srv://marlon1906ia_db_user:xXO96QBndFNNBbW4@helpapi.aykyf7k.mongodb.net/?appName=helpApi

spring.data.mongodb.database=help_system_tables

server.port=8080